### ISSUE TITLE
How to get user claims from RequestResourceOwnerPassword flow?

### ISSUE THREAD

**Issue by eldiosyeldiablo** [IdentityServer/IdentityServer2#835]
For our server to server api calls we are getting the OAuth token by calling the OAuth2Client.RequestResourceOwnerPasswordAsync method

Ex:
```csharp
var client = new OAuth2Client(
	new Uri("https://auth.example.com/IdSvr/issue/oauth2/token"),
	"clientId",
	"password");

var token = client.RequestResourceOwnerPasswordAsync("SampleClient", "password", "urn:protectedApi")
```

However, the claims is not full populated. How is it recommended that we get the claims populated?

When I say not fully populated the IClaimsRepository is not called so the claim set is very minimal.
Should there be an additional call by the client application to get the claim set like the OIDC flow does?

**Comment by pravinbhosale01** [comment]
If you are using JWT type of token, There are online JWT token decoder, one of them is http://jwt.io paste your token in textbox there and see decoded claims.
If you want to do that using code, you can find that in *HttpActionContext.Request.GetClaimsPrincipal().Claims* on Authorization level.
