### ISSUE TITLE
Having a login screen in the client side instead of Identity server side?

### ISSUE THREAD

**Issue by PreethiAdeline** [IdentityServer/IdentityServer2#845]
Hi,

I'm using Token based authentication ( with Authorisation Code Flow Grant) in MVC5  . I want to have a login screen in my MVC client instead of using Thinktecture login screen.
Can you please guide me on how i can meet the above requirement?

**Comment by leastprivilege** [comment]
This has been discussed many many times before. You can't - or you will lose features like SSO, external IdPs etc..
