### ISSUE TITLE
OpenID Connect Client is returning "Missing redirect URI"

### ISSUE THREAD

**Issue by DeeDeeLee** [IdentityServer/IdentityServer2#854]
Hi,

I am trying to create a "OpenID Connect Client"  that uses the Identity Server 2 as it's authenication source.

I have setup a "OpenID Connect" Client with the
 Redirect URI : "https://idsrv/auth/oidc/".

But after I login, I got the error message:

Error Processing Request

Missing redirect URI

I noticed that the URI it tried to redirect is "https://graph.windows.net", I really don't know where it come from.

/issue/oidc/authorize?response_type=code&client_id=Test&scope=openid profile email&nonce=N667da12c3c9cf&response_mode=form_post&resource=https://graph.windows.net&state=CQKYTnFkM9VrqbJ

Could anyone help please?
Thanks in advance

**Comment by leastprivilege** [comment]
I am not sure what you are trying to do but the resource parameter is Azure AD specific.

Generally we don't recommend to use IdSrv2 for any OIDC or OAuth2 work - it is deprecated in favour of IdentityServer3

**Comment by DeeDeeLee** [comment]
Thank you very much for your quick reply.

Actually I am trying to do the single sign-on for .Net, SharePoint and Moodle sites using Identity Server V2.5 . Now I can authenticate .Net and Sharepoint by using WS_Federation. For Moodle, I am trying to use "OpenID Connect" or "OAuth Client", but they both give me the errors. If these two are not recommended, what is your suggestion? For IdentityServer3, are there any release versions? I couldn't find Administration tool for it yet.

Thanks again.

**Comment by DeeDeeLee** [comment]
B.T.W I was hosting identity server 2 in Azure before. Now I moved it to out local server, but I still get the same error. 
Missing redirect URI
the url is:
https://idserver/issue/oidc/authorize?response_type=code&client_id=MoodleTest&scope=openid%20profile%20email&nonce=N559eb3ee6334f&response_mode=form_post&resource=https%3A%2F%2Fgraph.windows.net&state=9G4swwGUJSXRY6n

**Comment by DeeDeeLee** [comment]
Here is the more explanation of what we are doing:

" We did start with ID server v3, but the lack of an administration console that V2 has made it difficult for us to set up things. So we reverted back to ID server v2 since our use case doesn’t require any of the advanced features in V3. We are trying to set up an SSO between a SharePoint application which uses .NET Membership based FBA with a Moodle site

**Comment by leastprivilege** [comment]
Well - there is no redirect URI in your request. And as I said before - resource is a MS proprietary parameter supported only by Azure AD.

Since we don't support IdSrv2 anymore - I would recommend you use the source code and debug through to see what's going on.
