### ISSUE TITLE
redirecting to public facing pages

### ISSUE THREAD

**Issue by ntaylor95** [IdentityServer/IdentityServer2#855]
I am taking over this code from the original architect. All I want to do is add a "reset password" to the Thinktecture login screen that would redirect the user to a public facing page on my website. I guess because the whole domain is behind this SSO, it does not matter if my pages are setup to be public facing or private facing. So, my question is... can I add exceptions to the relying parties... like this url would need to be accessed outside the SSO... http://localhost/Public... but the relying party setup is http://localhost

**Comment by brockallen** [comment]
Why not just have a page (like the login page) in the HdentityServer host project that allow anonymous access?

**Comment by ntaylor95** [comment]
Great idea. This is my duh moment! Will work on it now 😄 thanks so much.

**Comment by ntaylor95** [comment]
I reset my password from my website using the API call: api/Password/reset/{guid}... I now have this public facing page on the Identity Server but all the API call are stored in the API project and I cannot call to the API becuase I am not an authorized user. I need the same exact behavior as with the API call: api/Password/reset/{guid}... anyway I can get that inside IdentityServer as an unauthenticated user who only knows their email address??????

**Comment by ntaylor95** [comment]
I found the public facing call in the API api/Password/reset/{email} = this returns a valid response, no email is being sent though.
