### ISSUE TITLE
localhost 44303 callback

### ISSUE THREAD

**Issue by simplynewbie** [IdentityServer/IdentityServer2#858]
Sorry, I asked this problem in issues of Authorization Server but Brock Allen seems busy so i ask here. 
( https://github.com/IdentityModel/AuthorizationServer/issues/252 )

but i'm not sure the-link-after-clicking-Allow be localhost:44303/callback or not. If yes, can i edit this address to another without https? I had Authorization Server to be https in IIS and i can not create more https for Identity Server in the same computer. 

My purpose is getting code and access token as your sample CodeFlow but using WPF (not WCF as other issues i read because i don't know anything about WCF except its name). 

Thank you.

**Comment by leastprivilege** [comment]
posting the same issues in multiple repos won't help. sorry.
