### ISSUE TITLE
PHP Client accessing WCF (RP)

### ISSUE THREAD

**Issue by satishkbg** [IdentityServer/IdentityServer2#866]
Is there any sample code or link where i can find details on how to make a PHP client call a WCF service which is a RP configured with thinktecture id-server. The wcf svc is hosted with WS2007FederationHttpBinding and TransportWithMessageCredential.

Is active-federation possible in PHP?

- Satish

**Comment by brockallen** [comment]
Your question is more about PHP libraries that do SOAP. I'd reach out to the PHP developer communities.
