### ISSUE TITLE
Pass whr to Identity Provider

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer2#877]
We have an ADFS with multiple Claim Provider Trusts. IdentityServer2 sits in the middle, between our application and this ADFS instance.

Now, we want to configure ADFS as Identity Provider on the IdentityServer2, but I don't see how we can force it to send a whr parameter along for selecting the correct Claim Provider on the ADFS.

Adding a whr parameter to the WS-Federation Endpoint url obviously doesn't work.

Is this scenario supported? Or any other way to work-around this?

**Comment by brockallen** [comment]
I don't recall us supporting this in IdSvr2 -- you can either change the source, or somehow hook the outbound response with an http module.

**Comment by huysentruitw** [comment]
I've hacked the code a little so I can configure the WS-Federation endpoint with additional ?whr=whatever parameter. Then this value gets extracted and used to set the `message.HomeRealm` property during sign-in.
