### ISSUE TITLE
Disappearing Client Secret

### ISSUE THREAD

**Issue by Napkin41** [IdentityServer/IdentityServer2#890]
Howdy,

Stumbled across this hub while trying to find a solution to a weird problem I'm having. In short, when I enter a client secret for an OAuth client that I've created, it disappears when I hit Save Changes. I've tried to check and see if maybe I didn't configure something properly but to no avail.

Am I missing something perhaps? Thanks!

**Comment by leastprivilege** [comment]
Greetings to the 90ies ;)

That's by design - the secrets gets stored hashed. You can't have it back in plain text.

**Comment by Napkin41** [comment]
Oh, I feel silly. So then I suppose that means we have to remember what we
set it to before it goes into the void. Thank you for your reply!
